### ISSUE TITLE
Not all subscriptions listed

### ISSUE THREAD

**Issue by lalamper** [dolevshor/Azure-Snapshots-Insights#1]
Hi!

First, congrats for this nice insight! :)

However, as far as I see, not all my subscriptions listed in the drop down menu. I think the subscription filters at directory switching does not count from this point of view.

Thanks!

**Comment by dolevshor** [comment]
Hi @lalamper ,

I have checked it, and it does need a fix.
I will handle it soon and let you know once it is done.

**Comment by dolevshor** [comment]
Hi @lalamper ,

Just to let you know that I fixed the 'Subscription' filter functionality.
I also added a new feature to delete multiple snapshots directly from the workbook.

Please share your feedback.

**Comment by lalamper** [comment]
Hi @dolevshor 
Thank you for your work! 😊😊
I will try it out soon!
Have a great day!

**Comment by lalamper** [comment]
Unfortunately, it seems that other issue came up. No subs listed at all.
![image](https://github.com/user-attachments/assets/97340eb5-963b-4025-bcfa-24f40139d19c)

**Comment by dolevshor** [comment]
@lalamper ,
Do you have any snapshots resources in your subscription(s) ?

Tou can check that by run this KQL query on Azure Resource Graph Explorer:

```kql
resources
where type =~ "microsoft.compute/snapshots"
```

**Comment by lalamper** [comment]
Ahh, okay, I see the issue.. :) The workbook shows subs only, where snapshots can be found. I extended the filter for other subs (where snapshots present) and now it shows them. Thanks!
